/*
 * fnirs-plugin: build.gradle
 */
buildscript {
    ext {
        vXnat = "1.10.0"
        vPluginVersion = "3.8.0"
        vPluginDescription = "ICR/XNAT OHIF Viewer Plugin"
        vEtherJ = "1.1.6"
    }
}

plugins {
    id "eclipse"
    id "idea"
    id "java"
    id "maven-publish"
    id "com.palantir.git-version" version "5.0.0"
    id "io.freefair.lombok" version "9.2.0"
    id "io.spring.dependency-management" version "1.1.7"
    id "net.linguica.maven-settings" version "0.5"
    id "org.nrg.xnat.build.xnat-data-builder" version "${vXnat}"
}

group = "org.nrg.xnatx.plugins"
version = vPluginVersion
description = vPluginDescription

repositories {
    mavenLocal()
    maven { url = "https://nrgxnat.jfrog.io/nrgxnat/libs-release" }
    maven { url = "https://nrgxnat.jfrog.io/nrgxnat/libs-snapshot" }
    maven { url = "https://www.dcm4che.org/maven2" }
    mavenCentral()
    maven { url = "https://jitpack.io"  }
    maven { url = "https://raw.github.com/nroduit/mvn-repo/master" }
}

// Use this configuration to put dependencies into the plugin jar
configurations {
    implementation.extendsFrom(implementAndInclude)
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

dependencyManagement {
    imports {
        mavenBom "org.nrg:parent:${vXnat}"
    }
    generatedPomCustomization {
        enabled = false
    }
}

dependencies {
    implementation "javax.servlet:javax.servlet-api"

    implementation("org.nrg.xnat:web") { transitive = false }
    implementation("org.nrg.xnat:xnat-data-models") { transitive = false }
    implementation("org.nrg.xdat:core") { transitive = false }
    implementation("org.nrg:automation") { transitive = false }
    implementation("org.nrg:config") { transitive = false }
    implementation("org.nrg:dicomtools") { transitive = false }
    implementation("org.nrg:dicom-xnat-mx") { transitive = false }
    implementation("org.nrg:dicom-xnat-sop") { transitive = false }
    implementation("org.nrg:framework")
    implementation("org.nrg:prefs") { transitive = false }

    implementation("turbine:turbine") { transitive = false }
    implementation("org.apache.velocity:velocity") { transitive = false }
    implementation "javax.inject:javax.inject:1"

    implementation "org.springframework:spring-web"
    implementation "org.springframework:spring-webmvc"
    implementation "org.springframework:spring-context"
    implementation "org.springframework.security:spring-security-core"

    implementation "io.springfox:springfox-swagger2"
    implementation "commons-io:commons-io"
    implementation "commons-codec:commons-codec"
    implementation "org.apache.commons:commons-lang3"
    implementation("io.projectreactor:reactor-core") { transitive = false }
    implementation("io.projectreactor:reactor-bus") { transitive = false }

    implementation("org.slf4j:slf4j-api") { transitive = false }
    implementation("org.slf4j:slf4j-log4j12") { transitive = false }
    implementation("dcm4che:dcm4che-core") { transitive = false }
    implementation("com.google.code.gson:gson") { transitive = false }

    // ICR DICOMweb
    // vDcm4che matching dcm4che5.version
    // in https://bitbucket.org/xnatdev/parent/src/master/pom.xml
    implementation("org.dcm4che:dcm4che-core") { transitive = false }
    implementation("org.dcm4che:dcm4che-image") { transitive = false }
    implementation("org.dcm4che:dcm4che-imageio") { transitive = false }
    implementAndInclude("org.dcm4che:dcm4che-json") { transitive = false }
    implementAndInclude("org.glassfish:jakarta.json:2.0.1")
    implementAndInclude("jakarta.json:jakarta.json-api:2.1.3")

    // Guava
    implementation("com.google.guava:guava") { transitive = false }
    implementation("com.fasterxml.jackson.core:jackson-annotations") { transitive = false }
    implementation("com.fasterxml.jackson.core:jackson-core") { transitive = false }
    implementation("com.fasterxml.jackson.core:jackson-databind") { transitive = false }
    // Logback
    implementation("ch.qos.logback:logback-classic") { transitive = false }
    implementation("ch.qos.logback:logback-core") { transitive = false }
     // EtherJ
    implementAndInclude("icr.etherj:etherj-core:${vEtherJ}") { transitive = false }

    testImplementation "org.slf4j:slf4j-nop"
    testImplementation "junit:junit"
}

test {
    useJUnitPlatform()
}

sourceSets {
    main {
        java {
            srcDir "build/xnat-generated/src/main/java"
        }
        resources {
            srcDir "build/xnat-generated/src/main/resources"
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

compileJava {
    dependsOn xnatDataBuilder
    options.fork = false
}

jar {
    doLast {
        if (!gradle.taskGraph.hasTask(":fatJar")) {
            logger.warn "WARNING: You should generally run xnatPluginJar instead of jar task for this plugin"
        }
    }
}

tasks.register("fatJar", Jar) {
    zip64 = true
    archiveClassifier = "fat"
    from {
        configurations.implementAndInclude.collect { it.isDirectory() ? it : zipTree(it) }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    with jar
}

// Pulls in the Jenkins BUILD_NUMBER environment variable if available.
def buildDate = new Date()
def buildNumber = System.getenv().BUILD_NUMBER?.toInteger() ?: "Manual"
def isDirty, branchName, gitHash, gitHashFull, commitDistance, lastTag, isCleanTag

try {
    def gitDetails = versionDetails()
    isDirty = gitVersion().endsWith ".dirty"
    branchName = gitDetails.branchName ?: "Unknown"
    gitHash = gitDetails.gitHash
    gitHashFull = gitDetails.gitHashFull
    commitDistance = gitDetails.commitDistance
    lastTag = gitDetails.lastTag
    isCleanTag = gitDetails.isCleanTag
} catch (IllegalArgumentException e) {
    logger.info "Got an error trying to read VCS metadata from git. It's possible this project is not under VCS control. Using placeholder values for manifest entries."
    isDirty = true
    branchName = "Unknown"
    gitHash = "None"
    gitHashFull = "None"
    commitDistance = 0
    lastTag = "None"
    isCleanTag = false
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes "Application-Name": vPluginDescription,
                "Build-Date": buildDate,
                "Build-Number": buildNumber,
                "Implementation-Version": vPluginVersion,
                "Implementation-Sha": gitHash,
                "Implementation-Sha-Full": gitHashFull,
                "Implementation-Commit": commitDistance,
                "Implementation-LastTag": lastTag,
                "Implementation-Branch": branchName,
                "Implementation-CleanTag": isCleanTag,
                "Implementation-Dirty": isDirty
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifacts {
                artifact fatJar
            }

            pom.withXml {
                def root = asNode()
                root.appendNode("name", vPluginDescription)
                root.appendNode("url", "https://bitbucket.org/icrimaginginformatics/ohif-viewer-xnat-plugin")
                root.appendNode("inceptionYear", "2019")

                root.appendNode("scm").with {
                    appendNode("url", "https://bitbucket.org/icrimaginginformatics/ohif-viewer-xnat-plugin")
                    appendNode("connection", "scm:https://bitbucket.org/icrimaginginformatics/ohif-viewer-xnat-plugin")
                    appendNode("developerConnection", "scm:git@bitbucket.org:icrimaginginformatics/ohif-viewer-xnat-plugin.git")
                }

                root.appendNode("licenses").appendNode("license").with {
                    appendNode("name", "3-Clause BSD License")
                    appendNode("url", "https://opensource.org/licenses/BSD-3-Clause")
                    appendNode("distribution", "repo")
                }

                root.appendNode("developers").with {
                    appendNode("developer").with {
                        appendNode("id", "jamesd")
                        appendNode("name", "James Darcy")
                        appendNode("email", "jamesd@icr.ac.uk")
                    }
                    appendNode("developer").with {
                        appendNode("id", "jpetts")
                        appendNode("name", "James Petts")
                        appendNode("email", "jpetts@icr.ac.uk")
                    }
                    appendNode("developer").with {
                        appendNode("id", "rherrick")
                        appendNode("name", "Rick Herrick")
                        appendNode("email", "rick@xnatworks.io")
                    }
                    appendNode("developer").with {
                        appendNode("id", "malsad")
                        appendNode("name", "Mo Alsad")
                        appendNode("email", "mo.alsad@gmail.com")
                    }
                }
            }
        }
    }
    repositories {
        maven {
            url = "https://nrgxnat.jfrog.io/nrgxnat/libs-${vPluginVersion.endsWith("-SNAPSHOT") ? "snapshot" : "release"}"
            // The value for name must match <id> in ~/.m2/settings.xml
            name = "XNAT_Artifactory"
        }
    }
}
